../../hdl/anu_core.v
../../hdl/alu.v
../../hdl/ID.v
../../hdl/extend32.v
../../hdl/memory.v
../../hdl/p_cntr.v
../../hdl/register_file.v
../../hdl/branch_unit.v
../../hdl/control_unit.v
../../hdl/top_tb.v